### ISSUE TITLE
Animate Learner Trajectory Visualization

### ISSUE THREAD

**Issue by bherr2** [cns-iu/learning-trajectories#10]
Update the learner trajectory visualization (Issue #9) to have a state where the student 'trajectory' through the course is animated. There is no specific guidance on exactly how the animation should look other than it should convey movement of the user through the different modules.

* It should play while the play button is pressed
* It should stop (and remember its current place) when the pause button is pressed
* It should reset the visualization to the 'static' non-animated state when the stop button is pressed
* It should have variables to alter the speed of the animation. The exact workings of this is undefined as there are many ways to do this. The simplest implementation can be number of seconds between 'hops'.

**Comment by axdanbol** [comment]
@mginda Should the animation continuously loop or stop once it is done after the user presses the play button?
