### ISSUE TITLE
Sprint Client Review: Open questions for the on visualization development 

### ISSUE THREAD

**Issue by mginda** [cns-iu/learning-trajectories#12]
This issue will be used to track developer insight needs that Michael will use to guide a review of the visualization with the client, to provide feedback that will guide future sprint development cycles.

Example questions:
- What tool labels would be relevant for the nodes and edges?
- What information about a student is relevant to display with the visualization?
- What filters on the student data set are relevant (demographics vs aggregate performance, clusters)? 
- What filters would be useful when filtering the network edge list?
- What supplementary components are missing?

**Comment by bherr2** [comment]
* How would you like to encode the edge thickness? Currently its a fixed size.

**Comment by mginda** [comment]
Excellent!
It does  run on my laptop. Great.
 
Node size in legend does not correspond to node size in vis. Any way to change this?
Just render legend circles small.
 
In future version, please
use professional type font for
Learning Trajectories: Architecture of Complex Systems, Fall 2016 - Person x
 
current version does not fit on my screen – need to scroll extensively.
k
