### ISSUE TITLE
Final touch-ups

### ISSUE THREAD

**Issue by mginda** [cns-iu/learning-trajectories#13]
- [x] Flatten edge curves
- [x] Add 1 px to left and right margins of layout
- [x] Update legend text -
   - Node color - "Module Type"
   - Node size - "# Interactions"
- [x] Add notation
    - "Node ordered by course module sequence."

**Comment by katyb** [comment]
+ Correct blue color for Direction in Legend
Thank you!
k

--
Katy Borner

**Comment by mginda** [comment]
Curve flattening did not look good, so was scrapped.
