### ISSUE TITLE
Add alternating background boxes to delineate weeks/hierarchy

### ISSUE THREAD

**Issue by GagsdName** [cns-iu/learning-trajectories#19]
* Background boxes with a grey color shade that does not conflict with the color of the edges to be added surrounding nodes in the visualization to delineate hierarchy. 
* The boxes should also have a label indicating the hierarchy level.

**Comment by mginda** [comment]
LC will need to support color selection

**Comment by lecross** [comment]
Need more info. Also need a timeline.

**Comment by bherr2** [comment]
@lecross I'll get you the details after the standup today at 10am. It'll mainly be choosing 2 or 3 colors to enhance the learning trajectories visualization. Timeline would be end of this week. We can put in colors now and will replace them with whatever you think works.

**Comment by GagsdName** [comment]
From @lecross - (for the moment, we can improvise based on how these work out)
* Light - #bdbdbd
* Mid -  #8a8a8a 
* Dark - #575757
* Pale for background label sections  - #f5f5f5
