### ISSUE TITLE
Add new course data

### ISSUE THREAD

**Issue by bherr2** [cns-iu/learning-trajectories#28]
@mginda will provide a new course with students to integrate

**Comment by mginda** [comment]
@bherr2 
The data files are available on the server at the following paths:
Student aggregate data set:
Y:\data\sow2-AM-course\analysis\studentActivity\MITxPRO+AMxB+1T2018-auth_users-LTN-set.csv
Student networks:
Y:\data\sow2-AM-course\networks\LTN-Set\Person{1-10}.json
