### ISSUE TITLE
Integrate student trajectory data

### ISSUE THREAD

**Issue by bherr2** [cns-iu/learning-trajectories#7]
* [x] Integrate student trajectory data (do not commit the json data, place in the raw-data directory). 
* [x] Include at least 2 students, try to find a few different edge cases (a ton of edges, few/zero edges, middle of the road number of edges, etc.)
* [x] Include interface definitions (ie export interface Module {}; }
* [x] Include a service facade (we won't worry about a real database right now, but the facade for accessing the data should still be how you get the data)

**Comment by bherr2** [comment]
The interface definition does not necessarily have to mirror the names in the JSON data. If we have better names (and also we should use lowerCamelCase for properties), then please do so. We can use Operators or wrappers to normalize the data.

**Comment by mginda** [comment]
I've updated the data description with one new field to vertices and edges descriptions, "sl", to capture information on self-loops in the network. These networks are now on the server.

**Comment by GagsdName** [comment]
Sample dataset of person files is at - **/projects/research/17-Boeing/data/sow1-PNAS-processingAnalysis-HERE/networks/lt-data**

**person1** - nodes=551, edges=1 <br />
**person2** - nodes=551, edges=238 <br />
**person3** - nodes=551, edges=719 <br />
**person4** - nodes=551, edges=812 <br />
**person5** - nodes=551, edges=6924 <br />

**person2** and **person3** were used by Michael for mockups before <br />
**person4** is the middle of the dataset

**Comment by bherr2** [comment]
The setup is more complicated than it needs to be... But good enough.

**Comment by mginda** [comment]
### Course information
Data was extracted from the edX course structure data file, which is what builds the node list for the LT networks.

#### Data set, includes:
 \\smb.cns.iu.edu\projects\research\17-Boeing\data\sow1-PNAS-processingAnalysis\course\
MITProfessionalX+SysEngxB1+3T2016-meta.csv

```
id - MITProfessionalX+SysEngxB1+3T2016 // course uuID
metadata.display_name - "Architecture of Complex Systems" // Full name of the course
term - "Fall 2016" // Term course was offered
category - "course" // always course, this category of module in course structure where data was extracted.
metadata.start // course start date 
metadata.end // course end date
metadata.enrollment_start // course enrollment start date 
metadata.enrollment_end // course enrollment end date 
```
